### ISSUE TITLE
Make able to set own DNS server address (like NextDNS)

### ISSUE THREAD

**Issue by ZhymabekRoman** [mansuf/requests-doh#1]
Thanks for the library! Might be good functionality to set own DOH address.

**Comment by mansuf** [comment]
I have made PR #2 that will close this issue. If you can test it, that would be helpful 👍

Usage:
```python
from requests_doh import add_dns_provider, DNSOverHTTPSSession

add_dns_provider("another-dns", "https://another-dns.example.com/dns-query")

session = DNSOverHTTPSSession("another-dns")
session.get("https://google.com")
```

**Comment by ZhymabekRoman** [comment]
Thanks! Works great! Tested using NextDNS.

**Comment by mansuf** [comment]
The PR has been merged and it will be released soon.

Thanks for the idea 💖
